# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(570, 500, 113, 32))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(690, 500, 113, 32))
        self.cancelButton.setObjectName("cancelButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 171, 471))
        self.groupBox.setObjectName("groupBox")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton11.setGeometry(QtCore.QRect(20, 70, 113, 32))
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton12.setGeometry(QtCore.QRect(30, 140, 113, 32))
        self.pushButton12.setObjectName("pushButton12")
        self.pushButton13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton13.setGeometry(QtCore.QRect(20, 210, 113, 32))
        self.pushButton13.setObjectName("pushButton13")
        self.pushButton14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton14.setGeometry(QtCore.QRect(30, 290, 113, 32))
        self.pushButton14.setObjectName("pushButton14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 0, 171, 471))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton21.setGeometry(QtCore.QRect(20, 70, 113, 32))
        self.pushButton21.setObjectName("pushButton21")
        self.pushButton22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton22.setGeometry(QtCore.QRect(20, 150, 113, 32))
        self.pushButton22.setObjectName("pushButton22")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 0, 211, 471))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 171, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 40, 151, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton31 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton31.setGeometry(QtCore.QRect(30, 270, 113, 32))
        self.pushButton31.setObjectName("pushButton31")
        self.pushButton32 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton32.setGeometry(QtCore.QRect(40, 380, 113, 32))
        self.pushButton32.setObjectName("pushButton32")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(630, 0, 181, 471))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton41 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton41.setGeometry(QtCore.QRect(20, 70, 113, 32))
        self.pushButton41.setObjectName("pushButton41")
        self.pushButton42 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton42.setGeometry(QtCore.QRect(20, 140, 113, 32))
        self.pushButton42.setObjectName("pushButton42")
        self.pushButton43 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton43.setGeometry(QtCore.QRect(30, 220, 113, 32))
        self.pushButton43.setObjectName("pushButton43")
        self.pushButton44 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton44.setGeometry(QtCore.QRect(30, 320, 113, 32))
        self.pushButton44.setObjectName("pushButton44")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton14.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton21.setText(_translate("MainWindow", "PushButton"))
        self.pushButton22.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton31.setText(_translate("MainWindow", "PushButton"))
        self.pushButton32.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton41.setText(_translate("MainWindow", "PushButton"))
        self.pushButton42.setText(_translate("MainWindow", "PushButton"))
        self.pushButton43.setText(_translate("MainWindow", "PushButton"))
        self.pushButton44.setText(_translate("MainWindow", "PushButton"))
