# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(730, 340, 113, 32))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(850, 340, 113, 32))
        self.cancelButton.setObjectName("cancelButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 131, 301))
        self.groupBox.setObjectName("groupBox")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton11.setGeometry(QtCore.QRect(10, 30, 113, 32))
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton12.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.pushButton12.setObjectName("pushButton12")
        self.pushButton13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton13.setGeometry(QtCore.QRect(10, 110, 113, 32))
        self.pushButton13.setObjectName("pushButton13")
        self.pushButton14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton14.setGeometry(QtCore.QRect(10, 150, 113, 32))
        self.pushButton14.setObjectName("pushButton14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 0, 131, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton21.setGeometry(QtCore.QRect(10, 30, 113, 32))
        self.pushButton21.setObjectName("pushButton21")
        self.pushButton22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton22.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.pushButton22.setObjectName("pushButton22")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 0, 251, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 231, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton31 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton31.setGeometry(QtCore.QRect(10, 150, 113, 32))
        self.pushButton31.setObjectName("pushButton31")
        self.lineEdit311 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit311.setGeometry(QtCore.QRect(60, 30, 113, 21))
        self.lineEdit311.setObjectName("lineEdit311")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 60, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit312 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit312.setGeometry(QtCore.QRect(60, 60, 113, 21))
        self.lineEdit312.setObjectName("lineEdit312")
        self.lineEdit313 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit313.setGeometry(QtCore.QRect(60, 90, 113, 21))
        self.lineEdit313.setObjectName("lineEdit313")
        self.lineEdit314 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit314.setGeometry(QtCore.QRect(60, 120, 113, 21))
        self.lineEdit314.setObjectName("lineEdit314")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(180, 30, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(180, 90, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(180, 120, 60, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton32 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton32.setGeometry(QtCore.QRect(10, 220, 113, 32))
        self.pushButton32.setObjectName("pushButton32")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(580, 0, 131, 301))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton41 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton41.setGeometry(QtCore.QRect(10, 30, 113, 32))
        self.pushButton41.setObjectName("pushButton41")
        self.pushButton42 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton42.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.pushButton42.setObjectName("pushButton42")
        self.pushButton43 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton43.setGeometry(QtCore.QRect(10, 110, 113, 32))
        self.pushButton43.setObjectName("pushButton43")
        self.pushButton44 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton44.setGeometry(QtCore.QRect(10, 150, 113, 32))
        self.pushButton44.setObjectName("pushButton44")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(720, 0, 261, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 190, 241, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton55 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton55.setGeometry(QtCore.QRect(10, 60, 113, 32))
        self.pushButton55.setObjectName("pushButton55")
        self.lineEdit551 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit551.setGeometry(QtCore.QRect(120, 30, 113, 21))
        self.lineEdit551.setObjectName("lineEdit551")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton51 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton51.setGeometry(QtCore.QRect(10, 30, 113, 32))
        self.pushButton51.setObjectName("pushButton51")
        self.pushButton52 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton52.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.pushButton52.setObjectName("pushButton52")
        self.pushButton53 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton53.setGeometry(QtCore.QRect(10, 110, 113, 32))
        self.pushButton53.setObjectName("pushButton53")
        self.pushButton54 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton54.setGeometry(QtCore.QRect(10, 150, 113, 32))
        self.pushButton54.setObjectName("pushButton54")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.pushButton11.setText(_translate("MainWindow", "1.1"))
        self.pushButton12.setText(_translate("MainWindow", "1.2"))
        self.pushButton13.setText(_translate("MainWindow", "1.3"))
        self.pushButton14.setText(_translate("MainWindow", "1.4"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Adaptive Threshold"))
        self.pushButton21.setText(_translate("MainWindow", "2.1"))
        self.pushButton22.setText(_translate("MainWindow", "2.2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3. Image Transformation"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3.1"))
        self.pushButton31.setText(_translate("MainWindow", "3.1"))
        self.label.setText(_translate("MainWindow", "Angle:"))
        self.label_2.setText(_translate("MainWindow", "Scale:"))
        self.label_3.setText(_translate("MainWindow", "Tx:"))
        self.label_4.setText(_translate("MainWindow", "Ty:"))
        self.label_5.setText(_translate("MainWindow", "degree"))
        self.label_6.setText(_translate("MainWindow", "pixel"))
        self.label_7.setText(_translate("MainWindow", "pixel"))
        self.pushButton32.setText(_translate("MainWindow", "3.2"))
        self.groupBox_6.setTitle(_translate("MainWindow", "4. Convolution"))
        self.pushButton41.setText(_translate("MainWindow", "4.1"))
        self.pushButton42.setText(_translate("MainWindow", "4.2"))
        self.pushButton43.setText(_translate("MainWindow", "4.3"))
        self.pushButton44.setText(_translate("MainWindow", "4.4"))
        self.groupBox_5.setTitle(_translate("MainWindow", "5. LeNet"))
        self.groupBox_7.setTitle(_translate("MainWindow", "5.5"))
        self.pushButton55.setText(_translate("MainWindow", "5.5"))
        self.label_8.setText(_translate("MainWindow", "Test image index:"))
        self.pushButton51.setText(_translate("MainWindow", "5.1"))
        self.pushButton52.setText(_translate("MainWindow", "5.2"))
        self.pushButton53.setText(_translate("MainWindow", "5.3"))
        self.pushButton54.setText(_translate("MainWindow", "5.4"))
